// The roadmap's pure half — ADR 0021: validating an untrusted body into the document the db stores,
// and rendering it as Markdown for the caller to commit. The bridge never writes that file: the
// export is one way, board to repo, and nothing reads it back.

import { ROADMAP_STATUSES, type Roadmap, type RoadmapItem, type RoadmapStatus } from "./db.ts";

const MAX_ITEMS = 200;
const MAX_VISION = 20_000;
const MAX_NAME = 200;
const MAX_GOAL = 2_000;

/** Shape of `PUT /api/roadmap`: `vision`, `items`, and the `revision` the caller read (0 for none). */
export function parseRoadmapBody(
  v: unknown,
): { ok: true; value: { repoPath: string; vision: string; items: RoadmapItem[]; revision: number } } | { ok: false; error: string } {
  if (typeof v !== "object" || v === null) return { ok: false, error: "bad body" };
  const o = v as Record<string, unknown>;
  if (typeof o.repoPath !== "string" || !o.repoPath.startsWith("/")) return { ok: false, error: "repoPath must be an absolute path" };
  if (typeof o.revision !== "number" || !Number.isInteger(o.revision) || o.revision < 0)
    return { ok: false, error: "revision must be the whole number you read (0 for a new roadmap)" };
  const vision = o.vision ?? "";
  if (typeof vision !== "string" || vision.length > MAX_VISION) return { ok: false, error: "bad vision" };
  if (!Array.isArray(o.items) || o.items.length > MAX_ITEMS) return { ok: false, error: "items must be a list" };
  const seen = new Set<string>();
  const items: RoadmapItem[] = [];
  for (const raw of o.items as unknown[]) {
    const it = (typeof raw === "object" && raw !== null ? raw : {}) as Record<string, unknown>;
    if (typeof it.name !== "string" || it.name.trim() === "" || it.name.length > MAX_NAME) return { ok: false, error: "every item needs a name" };
    const goal = it.goal ?? "";
    if (typeof goal !== "string" || goal.length > MAX_GOAL) return { ok: false, error: "bad goal" };
    const status = it.status ?? "planned";
    if (!ROADMAP_STATUSES.includes(status as RoadmapStatus)) return { ok: false, error: `status must be one of ${ROADMAP_STATUSES.join(", ")}` };
    if (it.id !== undefined && (typeof it.id !== "string" || it.id.trim() === "")) return { ok: false, error: "bad item id" };
    const id = typeof it.id === "string" ? it.id.trim() : crypto.randomUUID().slice(0, 8);
    if (seen.has(id)) return { ok: false, error: `duplicate item id ${id}` };
    seen.add(id);
    items.push({ id, name: it.name.trim(), goal: goal.trim(), status: status as RoadmapStatus });
  }
  return { ok: true, value: { repoPath: o.repoPath, vision: vision.trim(), items, revision: o.revision } };
}

/** The roadmap as Markdown. Pure. ponytail: phase progress is not rendered — add if the repo file wants it. */
export function roadmapMarkdown(name: string, r: Pick<Roadmap, "vision" | "items" | "revision">): string {
  const lines = [
    `<!-- Generated by Collie Board, revision ${r.revision}. Edit the roadmap in the board, not here. -->`,
    `# Roadmap — ${name}`,
  ];
  if (r.vision) lines.push("", r.vision);
  r.items.forEach((it, i) => {
    lines.push("", `## ${i + 1}. ${it.name}${it.status === "planned" ? "" : ` — ${it.status}`}`);
    if (it.goal) lines.push("", it.goal);
  });
  return lines.join("\n") + "\n";
}
